format = "$all"
add_newline = false

[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold blue)"
vicmd_symbol = "[](bold yellow)"
format = "$symbol "

[package]
disabled = true

[hostname]
ssh_only = true
format = "[$hostname](bold cyan) in "
disabled = false

[username]
style_user = "purple bold"
style_root = "red bold"
format = "[$user]($style) in "
show_always = true
disabled = false

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1
disabled = false

[line_break]
disabled = false

[java]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "
